<?php

use Drupal\node\NodeInterface;
use Drupal\media\MediaInterface;
use Drupal\block\Entity\Block;

/**
 * @file Theme function for the LocalGovDrupal.org Theme theme.
 */

 /**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Add custom block theme suggestion based on block type and display.
 */
function lgd_org_theme_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // View mode suggestion for custom blocks.
  if (isset($variables['elements']['#configuration']['view_mode'])) {
    $view_mode = $variables['elements']['#configuration']['view_mode'];
    $suggestions[] = 'block__' . $view_mode;
  }
  else {
    $view_mode = NULL;
  }

  // Region suggestion for blocks in panels.
  if (isset($variables['elements']['#configuration']['region'])) {
    $region = $variables['elements']['#configuration']['region'];
    $suggestions[] = 'block__' . $region;
    if (isset($variables['elements']['#configuration']['provider'])) {
      $provider = $variables['elements']['#configuration']['provider'];
      $suggestions[] = 'block__' . $region . '__' . $provider;
    }
  }
  // Region suggestion for blocks in Drupal.
  if (isset($variables['elements']['#id'])) {
    if ($block = Block::load($variables["elements"]["#id"])) {
      $region = $block->getRegion();
      $suggestions[] = 'block__' . $region;
      $suggestions[] = 'block__' . $region . '__' . $variables['elements']['#base_plugin_id'];
      $suggestions[] = 'block__' . $region . '__' . $variables['elements']['#id'];
      $suggestions[] = 'block__' . $region . '__' . $variables['elements']['#base_plugin_id'] . '__' . $variables['elements']['#id'];
    }
  }

  // Custom Blocks (Bundles and view mode).
  if ($variables['elements']['#base_plugin_id'] === 'block_content'
    && isset($variables['elements']['content']['#block_content'])) {
    // Bundle type.
    $bundle = $variables['elements']['content']['#block_content']->bundle();
    $suggestions[] = 'block__' . $region . '__' . $bundle;
    if ($view_mode = $variables['elements']['content']['#view_mode']) {
      $suggestions[] = 'block__' . $region . '__' . $bundle . '__' . $view_mode;
      $suggestions[] = 'block__' . $bundle . '__' . $view_mode;
    }
    $suggestions[] = 'block__' . $bundle;
  }
}


/**
 * Implements hook_preprocess_HOOK() for hook_preprocess_paragraph().
 */
function lgd_org_theme_paragraphs_preprocess_paragraph(&$variables) {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  if ($paragraph->bundle() === 'localgov_link') {
    $variables['attributes']['class'][] = 'new-class';
  }
}


/**
 * Implements hook_preprocess_page().
 */
function lgd_org_theme_preprocess_page(&$variables) {
  $variables['#attached']['drupalSettings']['responsive_menu']['custom'] = [
  'options' => [
    //  'navbar' => [
    //    'add' => TRUE,
    //    'title' => 'This is a test',
    //],
    "offCanvas" => [
      "position"=> "right",
    ]
  ],
  //'config' => [
  //  'classNames' => [
  //    'selected' => 'my-custom-menu--active-trail',
  //  ],
  //]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lgd_org_theme_preprocess_block(&$variables): void {
  $route_match = Drupal::routeMatch();
  $route = $route_match->getRouteName();

  if ($variables['plugin_id'] === 'localgov_page_header_block') {

    // Check if we are on a node page, latest version or a preview link.
    if ($route === 'entity.node.canonical' || $route === 'entity.node.latest_version' || $route === 'entity.node.preview_link') {
      $node = $route_match->getParameter('node');
      $node_status = $node->isPublished();
      $node_type = $node->getType();


      if ($node_type === 'localgov_services_landing' || $node_type === 'localgov_services_sublanding'|| $node_type === 'localgov_newsroom'){
        $node_summary = $node->field_summary->value;
        $variables['content'][0]['#lede'] = $node_summary;
      }
      if ($node_type === 'localgov_page'){
        $node_summary = $node->	localgov_page_summary->value;
        $variables['content'][0]['#lede'] = $node_summary;
      }
      //if ($node_type === 'localgov_guides_page' && theme_get_setting('localgov_base_localgov_guides_stacked_heading') === TRUE) {
      //  $node_title = $node->getTitle();
      //  $parent_title = $node->get('localgov_guides_parent')->entity->getTitle();

      //  $variables['content'][0]['#title'] = $node_title;
      //  $variables['content'][0]['#subtitle'] = $parent_title;
      //}
    }
  }
}
