<?php

function lgd_org_blocks_theme($existing, $type, $theme, $path) {
  return [
    'lgd_org_blocks' => [
      'variables' => [
        'number' => NULL,
        'content' => NULL,
      ],
    ],
    'lgd_org_newsletter' => [
      'variables' => [
        'number' => NULL,
        'content' => NULL,
      ],
    ],
    'lgd_org_builtwith' => [
      'variables' => [
        'slogan' => NULL,
        'content' => NULL,
      ],
    ],
    'lgd_org_mailchimp' => [
      'variables' => [
        'slogan' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
