block.settings.lgd_org_blocks_blocks_3:
  type: block_settings
  label: 'Blocks block 3'
  mapping:
    number:
      type: string
      label: Number
    content:
      type: string
      label: Content
